all: mainStackUsingALinkedList mainQueueUsingALinkedList mainStackUsingAnArray


mainStackUsingALinkedList: mainStackUsingALinkedList.cpp
	g++ mainStackUsingALinkedList.cpp -o mainStackUsingALinkedList

mainStackUsingAnArray: mainStackUsingAnArray.cpp
	g++ mainStackUsingAnArray.cpp -o mainStackUsingAnArray

mainQueueUsingALinkedList: mainQueueUsingALinkedList.cpp
	g++ mainQueueUsingALinkedList.cpp -o mainQueueUsingALinkedList


clean:
	rm *.exe
